
development:
  adapter: postgresql
  database: oppcis_dev
  username: postgres
  password: admin
  host: localhost

test:
  adapter: postgresql
  database: oppcis_test
  username: postgres
  password: admin
  host: localhost

production:
  adapter: postgresql
  database: oppcis_prod
  username: postgres
  password: admin
